interpreter/src/Makefile
port/src/encoder/Makefile
port/src/Makefile
port/src/Makefle_ch
thread/src/Makefile
vmcore/src/verifier-3363/Makefile
vmcore/src/Makefile
em/src/Makefile
vmi/src/Makefile
jitrino/src/Makefile
gc_gen/src/makefile
